

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var jStates = JStates.FromJson(jsonString);

namespace MembershipPortal.core.Seed
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public class StateProps
    {

        public int id { get; set; }


        public string name { get; set; }


        public int country_id { get; set; }


        public string CountryCode { get; set; }


        public long FipsCode { get; set; }

        [JsonProperty("iso2")]
        public string Iso2 { get; set; }

        [JsonProperty("latitude")]
        public string Latitude { get; set; }

        [JsonProperty("longitude")]
        public string Longitude { get; set; }


        public DateTimeOffset CreatedAt { get; set; }


        public DateTimeOffset UpdatedAt { get; set; }

        public long Flag { get; set; }

        [JsonProperty("wikiDataId")]
        public string WikiDataId { get; set; }
    }



}

